### ISSUE TITLE
ARIN whois dump URL at irrexplorer.nlnog.net is 404

### ISSUE THREAD

**Issue by bluikko** [pierky/arouteserver#77] opened 2021-07-06 04:41 UTC
The ARIN whois dump URL http://irrexplorer.nlnog.net/static/dumps/arin-whois-originas.json.bz2 now gives a 404. Probably because http://irrexplorer.nlnog.net/ now redirects to a irrexplorer.dashcare.nl site.

**Comment by ymer66** [comment] 2021-07-06 12:54
The download seems to be available again. Anyhow seems to be a good time to prepare for an alternative source direct a ARIN.

**Comment by bluikko** [comment] 2021-07-08 10:59
I guess it was just an oversight when the site was being worked on / redirected.

4 hours after I prodded one of the admins it was acknowledged and fixed quickly. I guess it's a pretty good home for the file or at least "the support" is available and responsive if/when problems do happen.

**Comment by pierky** [comment] 2021-07-18 09:16
Hello everyone,

thanks for reporting this issue.

The code and the configuration are already able to deal with a different URL to download the ARIN DB from. The config parameter to change in that case is `filtering.irrdb.use_arin_bulk_whois_data.source` (and similarly for `use_registrobr_bulk_whois_data`). In 9aff0c0ac5908c47ba22fe8398d3ffdd57929d5b I've modified the error message that is shown when issues like this one happen, in a way to provide a hint to the user. The new error message looks like this now:

```
ARouteServer 2021-07-18 11:10:01,777 ERROR Error while retrieving ARIN Whois DB dump from http://irrexplorer.nlnog.net/static/dumps/arin-whois-originas.json.bz2: [reason of the error] - The error occurred while loading the IRR data from http://irrexplorerAA.nlnog.net/static/dumps/arin-whois-originas.json.bz2. If the data was moved to a different location, it is possible to adjust the configuration by changing the value of 'filtering.irrdb.use_arin_bulk_whois_data.source' inside the general.yml file.
```

Since the issue is no longer existing and the original URL is working, I'll not change the default one shipped with the default config of ARouteServer (even because I'm not aware of that DB being available elsewhere at the moment).

Going to close this for the time being. Please reopen if you think there's more to do here.

**Closed by pierky** 2021-07-18 09:16 UTC
